name: source

on: [push, pull_request]

jobs:
  style:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: TABs
      run: .github/workflows/source/hasTabs
    - name: End-of-Line whitespaces
      run: .github/workflows/source/hasEOLwhiteSpace
    - name: Proper file names in Examples
      run: .github/workflows/source/wrongFileNameInExamples
    - name: Examples are tested
      run: .github/workflows/source/inputsNotTested
